title: Shubhan Kamat # your name (or website title) here
logo: "/images/Shubhan Kamat Photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc Data Science student at Lancaster University with an undergraduate degree in mathematics. Skilled in Python, R and SQL.  
  <br><br>
  This portfolio is a summary of the projects I have comlpeted in academic and personal capacity and is intended to serve as a tool for potential employers to judge my credentials. 
  <br><br>
  <a href="https://www.linkedin.com/in/shubhankamat/>View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

