title: Shubhan Kamat # your name (or website title) here
logo: "/images/Shubhan Kamat Photo.jpg?raw=true&width=100&height=100" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc Data Science student at Lancaster University with an undergraduate degree in mathematics. Have a keen interest in Machine Learning, Deep Learning, Reinforcement Learning and their applications in various domains. Proficient in Python, R and SQL.  
  <br><br>
  <a href="https://www.linkedin.com/in/shubhankamat/>View My Resume</a>
  


